### ISSUE TITLE
4월 진행 이슈

### ISSUE THREAD

**Issue by ghojeong** [java-squid/2022-jubilant#19]
주제: 서버리스 컴퓨팅

공부를 반드시 해야만 할게 생겨서 까먹지 않도록, 미리 이슈 등록을 해보았습니다.
등록이 부적절하다 싶으면 바로 Close 하겠습니다.

# 세미나 발표 준비

<img width="733" alt="스크린샷 2022-03-22 오전 10 36 19" src="https://user-images.githubusercontent.com/38595650/159390093-a949f354-d5c9-443f-b7fb-078d5f367985.png">

# [읽어야 할 논문](https://github.com/java-squid/2022-jubilant/files/8320215/vHive_ASPLOS2021.pdf)

<img width="480" alt="흑우" src="https://user-images.githubusercontent.com/38595650/159390326-f43192dd-898c-4b52-9f28-ee0b5ef46307.png">

**Comment by 102092** [comment]
@jypthemiracle @kyupid @Hyune-c 
다른 분들도 코멘트로 진행 희망 이슈 달아주시면 감사하겠습니다.

**Comment by Hyune-c** [comment]
### naver.com 을 쳤을 때 무슨 일이 일어나는가?

![image](https://user-images.githubusercontent.com/55722186/160236387-f937a34c-6802-492d-bf5a-91e0aef41c90.png)

> 인터넷 치면 많이 나오는 주제로 보통 위 그림만을 설명하곤 한다.
> 이것을 질문 의도와 답변 의도가 포함된 면접 문제 버전으로 각색한다.

- naver.com의 서버를 찾기 위한 과정
    - DNS
- 서버까지 가는 과정
    - OSI7 계층이지만 요즘은 TCP/IP 4계층으로 설명하면 된다.
    - HTTP 통신을 위한 핸드 쉐이크 과정
- 서버까지 오는 과정에서 인프라는?
    - 라우트 53, LB, ECS 등
- 서버에 오면 Spring 동작은?
    - 디스패쳐 서블릿

**Comment by kyupid** [comment]
- Spring Data JPA 가 동작하는 방식
- JPA 에서 N + 1 문제는 무엇인가? 
- JPA 를 사용하는 이유 ( = SQL Mapper가 아니라 ORM을 사용하는 이유?)
- JPA 영속성 컨텍스트란 무엇인가?

**Comment by 102092** [comment]
#### 데이터베이스 성능 개선 작업에 대해

- Isolation level In JPA
- optional) Remove FK
- optional) Transaction separation

**Comment by Hyune-c** [comment]
### 면접 경험 & 전략 공유
- 최소 1개 회사를 대상으로 2차 면접까지의 경험을 공유합니다.
- 너무 적은 분량이 될 줄알고 안하려고 했는데, 정리하고 나니 A4 2장 분량 이상이 나와 공유할만 할 것 같습니다.
- f-lab 멘토님의 첨삭과 저의 면접 전략도 일부 공개합니다.
- 4/10일에 발표로 진행되며, 문서는 사전에 일부만 공개됩니다.

**Comment by jypthemiracle** [comment]
## Jackson Library는 DTO와 어떻게 mapping 하는가
* default constructor가 있을 때는 어떻게 작동하는가?
* 만약, 없다고 하면 어떻게 작동하는가?
