### ISSUE TITLE
첫 사이클 하고 싶은 주제 공유

### ISSUE THREAD

**Issue by kyupid** [java-squid/2022-jubilant#4]
### Spring OAuth
spring-boot-starter-oauth2-client 에서 처음 회원가입(로그인) 시에
회사 서비스에서 추가적인 정보입력을 받고 완료를 하고싶어 커스터마이징을 해야함.
스프링 시큐리티와 스프링 OAuth에 대한 이해가 없어서인지 헤매는 중.
[HttpSecurity - OAuth2LoginConfigurer 설정](https://traeper.tistory.com/212)를 해야할 거같지만
느낌상 이렇게 해야할거 같은 것 뿐이지 근거를 생각해낼 수 없음.
근본적으로 스프링 OAuth에 대한 이해가 필요해 보임.

#### 내가 아는 쿠키와 세션
HTTP 프로토콜은 기본적으로 stateless(무상태)이다.
하지만 로그인 등 사용자의 상태를 유지하기 위한 방법이 필요.
쿠키는 클라이언트(브라우저)에 한번 로그인한 정보를 저장해두고
서버에 요청할때마다 쿠키를 같이 넣는 형태.
쿠키 방법은 보안에 취약함.
세션은 서버에서 사용자마다 페이지에서 벗어날때까지 정보를 저장함
좋은점은 서버에서 사용자정보를 관리하기때문에 쿠키보다 보안에 유리.
안좋은점은? 사용자가 많아질수록 통신비가 늘어나기때문에 서버에 부담.
그 이상 모르겠음.

JWT는 브라이언이 유튜브에서 말했던 공식문서가 jwt같다라는 말밖에 생각이안남.
그래서 정리가 필요함

### 다른것들
낼 미팅때까지 생각해보겠음

**Comment by Hyune-c** [comment]
## Spring OAuth
- Spring Security 의 흐름을 Custom 하는 것부터 다루었으면 좋겠다.
- Spring OAuth 는 Deprecate 되었다. [oauth-repo](https://github.com/spring-projects/spring-security-oauth)
  - 하지만 OAuth2 는 사용법이 꽤 틀리기에 마이그의 길이 험난할 것으로 보인다.

## JWT
- 본인은 Security + JWT 로 활용하여 회사 시스템에 구현하였다. 
- Cookie, Session 의 문제를 대부분 해결할 수 있는 방법이기에 추천한다.

**Comment by Hyune-c** [comment]
## Spring OAuth
- Spring Security 의 흐름을 Custom 하는 것부터 다루었으면 좋겠다.
- Spring OAuth 는 Deprecate 되었다. [oauth-repo](https://github.com/spring-projects/spring-security-oauth)
  - 하지만 OAuth2 는 사용법이 꽤 틀리기에 마이그의 길이 험난할 것으로 보인다.

## JWT
- 본인은 Security + JWT 로 활용하여 회사 시스템에 구현하였다. 
- Cookie, Session 의 문제를 대부분 해결할 수 있는 방법이기에 추천한다.

**Comment by kyupid** [comment]
답변 감사합니다 🙂

Spring OAuth와 OAuth2를 혼동했습니다. 신규 프로젝트이고 OAuth2를 적용했습니다.

말씀하신대로 Spring security 먼저 공부해보겠습니다

**Comment by Hyune-c** [comment]
ㅇㅎ. Spring OAuth 라고 표현하셨길래 이미 구현되어 있는 것에 일부만 커스텀하시는 뜻으로 이해했네요.
OAuth2 는 저도 안해봤는데 (난이도 대비 필요성을 느끼지 못함) 공부하시면서 정보 공유 받으면 좋겠네요~

**Comment by kyupid** [comment]
### 주제 선정 끝
- Cookie vs Session vs JWT A4 1장~2장 분량으로 처음 읽는 사람이 이해할 정도의 문서 작성 목표하겠음 
- 작성 후에 다음 사이클을 위한 Spring security custom
